### ISSUE TITLE
Links on ttsautomate.com do not work

### ISSUE THREAD

**Issue by avsaase** [CaffeineAU/TTSAutomate#29]
Several links on TTSAutomate.com do not work. For example, on the how-to page, clicking "Working with Phrase Files" changes the url from `http://www.ttsautomate.com/howto.html#` to `http://www.ttsautomate.com/howto.html#CreatePhraseFile` as if there is a heading with that title on the same page, but there isn't.

**Comment by CaffeineAU** [comment]
You are correct. It's unfinished.

Thanks for your interest though. I do appreciate the feedback 😎

**Comment by avsaase** [comment]
No worries, and thanks for this software. 

I struggled making a phrase file, so I wanted to see how the csv file for importing needs to be formatted. Is there any documentation on that?

**Comment by CaffeineAU** [comment]
Are you creating your own file or are you trying to import another existing file?

If you're creating your own, I'd suggest using the native psv (pipe separated variable) file that TTSAutomate supports.
You can create it from within TTSAutomate or using an external text editor.

The format is each phrase on one line.

`<folder>|<filename>|your phrase to speak here
`

Please make sure to use a carriage return and line feed character to end each line (Windows style) rather than just a line feed (Unix style)

**Comment by CaffeineAU** [comment]
If you're tying to import a csv file (such as the openTX default sounds file) using Open Phrase File... -> Import CSV FIle... then please make sure it adheres to the following format:

`<folder>/;<filename>;your phrase to speak here
`
